name: reusable flake build (macos)
on:
  workflow_call:
    inputs:
      package:
        default: default
        required: false
        type: string
    secrets:
      cachix_auth_token:
        required: false

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        include:
          - runner: macos-15-intel
            system: x86_64-darwin
          - runner: macos-15
            system: aarch64-darwin
    runs-on: ${{ matrix.runner }}
        
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: wawwior
          authToken: ${{ secrets.cachix_auth_token }}

      - run: nix build .\#packages.${{ matrix.system }}.${{ inputs.package }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package }}-${{ matrix.system }}
          path: result
