---
name: check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - name: x86_64-linux
            runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check
